version : "3"
services:
  backend:
    image: shop-b
    build: ./backend-django
    ports:
      - 8000:8000
    volumes:
      - ./database:/app/database/
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"

  frontend:
    image: shop-f
    build: ./frontend-reactjs
    ports:
      - 8001:8001

